--YouEduApp base script


CREATE SCHEMA YOUEDUAPP;

USE YOUEDUAPP;



CREATE TABLE CATEGORY(
    CATEGORYID    		INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORYNAME   	VARCHAR(255),    	
	CATEGORY_PARENT  INT NULL ,		
    DATECREATED     		DATETIME  DEFAULT NOW(),
	CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (CATEGORY_PARENT) REFERENCES CATEGORY (CATEGORYID)
);

--MySQL Table Creation
CREATE TABLE VIDEO(
    ID         			INT PRIMARY KEY AUTO_INCREMENT,
    VIDEOURL   			VARCHAR(255),
    VIDEONAME   		VARCHAR(255),
    VIDEODESC  		VARCHAR(2048),	
	CATEGORY			INT NULL ,	
    DATECREATED     	DATETIME  DEFAULT NOW(),
	CONSTRAINT FK_VIDEO_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES CATEGORY (CATEGORYID)
);



    