--YouEduApp base script


CREATE SCHEMA YOUEDUAPP;


--MySQL Table Creation
CREATE TABLE VIDEO(
    ID         			INT PRIMARY KEY AUTO_INCREMENT,
    VIDEOURL   		VARCHAR(255),
    VIDEONAME   		VARCHAR(255),
    VIDEODESC  		VARCHAR(2048),
    DATECREATED     TIMESTAMP DEFAULT NOW()
);